#!name=获取联通 cookie
#!desc=YAYA 联通 cookie 小组件用到
#!system=ios

[Script]
Rewrite: 获取联通cookie = type=http-request,pattern=^https:\/\/m\.client\.10010\.com\/serviceimportantbusiness\/smart\/smartwisdomCommonNew,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/jaychoubaby/Script/main/quantumultX/task/10010/10010.cookie.js,script-update-interval=0

[MITM]
hostname = %APPEND% act.10010.com, m.client.10010.com